const jsonData = [
    {
        "id": 1,
        "path": "partiful",
        "image": "partiful",
        "title": "PARTIFUL",
        "duration": "a 3 weeks project", 
        "time": "April 2024",
        "team": "Ivery Chen, Dave Song, Sohum Sanu, Viviana Wei",
        "role": "UIUX Design",
        "tools": "Figma, Loom",
        "eventName": "Partiful Events Page Redesign",
        "description": "Redesigned the Partiful Events Home Page.",
        "categories": ["Prototyping", "UIUX Design", "Figma"]
    },
    {
        "id": 2,
        "path": "foam",
        "image": "foam",
        "title": "FOAM",
        "duration": "a 3 weeks project", 
        "time": "April 2024",
        "Team": "Ivery Chen, Dave Song, Sohum Sanu, Viviana Wei",
        "Role": "UIUX Design",
        "Tools": "Figma, Loom",
        "eventName": "Foam Web App",
        "description": "Designed the Pinterest for local artists discovery.",
        "categories": ["Frontend", "Prototyping", "UIUX Design", "Figma", "React", "Javascript", "HTML", "CSS"]
    },
    {
        "id": 3,
        "path": "sf",
        "image": "sf",
        "title": "FUNCHEAPSF",
        "duration": "a 3 weeks project", 
        "time": "April 2024",
        "Team": "Ivery Chen, Dave Song, Sohum Sanu, Viviana Wei",
        "Role": "UIUX Design",
        "Tools": "Figma, Loom",
        "eventName": "FunCheapSF Redesign",
        "description": "Redesigning funcheapsf.com.",
        "categories": [ "Frontend", "Prototyping", "UIUX Design", "Figma", "Javascript", "HTML", "CSS"]
    },
    {
        "id": 4,
        "path": "drivealive",
        "image": "drivealive",
        "title": "DRIVEALIVE",
        "duration": "a 3 weeks project", 
        "time": "April 2024",
        "Team": "Ivery Chen, Dave Song, Sohum Sanu, Viviana Wei",
        "Role": "UIUX Design",
        "Tools": "Figma, Loom",
        "eventName": "DriveAlive",
        "description": "A Computer Vision project that detects driver drowsiness.",
        "categories": [ "Frontend", "Prototyping", "UIUX Design", "Figma", "Computer Vision", "Python"]
    },
    {
        "id": 5,
        "path": "bayer",
        "image": "bayer",
        "title": "BAYER",
        "duration": "a 3 weeks project", 
        "time": "April 2024",
        "Team": "Ivery Chen, Dave Song, Sohum Sanu, Viviana Wei",
        "Role": "UIUX Design",
        "Tools": "Figma, Loom",
        "eventName": "Bayer VR",
        "description": "An end-to-end Unity training app to each drone flyers how to operate drones.",
        "categories": [ "Unity", "AR/VR/MR", "UX Research", "Blender", "Substance Painter", "AWS", "Oculus", "C#"]
    },
    {
        "id": 6,
        "path": "panda",
        "image": "panda",
        "title": "PANDA",
        "duration": "a 3 weeks project", 
        "time": "April 2024",
        "Team": "Ivery Chen, Dave Song, Sohum Sanu, Viviana Wei",
        "Role": "UIUX Design",
        "Tools": "Figma, Loom",
        "eventName": "Panda",
        "description": "Kahoot-style multiplayer game.",
        "categories": [ "Frontend", "Backend", "Prototyping", "UIUX Design", "React", "Javascript", "HTML", "CSS"]
    },
    {
        "id": 7,
        "path": "skim",
        "image": "skim",
        "title": "SKIM",
        "duration": "a 3 weeks project", 
        "time": "April 2024",
        "Team": "Ivery Chen, Dave Song, Sohum Sanu, Viviana Wei",
        "Role": "UIUX Design",
        "Tools": "Figma, Loom",
        "eventName": "Skim",
        "description": "A Haiku-from-novel game",
        "categories": [ "Unity", "Game Design", "C#", "MQTT"]
    },
    {
        "id": 8,
        "path": "magritte",
        "image": "magritte",
        "title": "MAGRITTE VR",
        "duration": "a 3 weeks project", 
        "time": "April 2024",
        "Team": "Ivery Chen, Dave Song, Sohum Sanu, Viviana Wei",
        "Role": "UIUX Design",
        "Tools": "Figma, Loom",
        "eventName": "Magritte VR",
        "description": "If Magritte had access to VR technology, what would his paintings be like?",
        "categories": [ "Unity", "AR/VR/MR", "Blender", "C#"]
    },
    {
        "id": 9,
        "path": "nasa_suits",
        "image": "nasa_suits",
        "title": "NASA SUITS",
        "duration": "a 3 weeks project", 
        "time": "April 2024",
        "Team": "Ivery Chen, Dave Song, Sohum Sanu, Viviana Wei",
        "Role": "UIUX Design",
        "Tools": "Figma, Loom",
        "eventName": "NASA SUITS",
        "description": "Mixed Reality Hololens app for NASA Suits Challenge.",
        "categories": [ "Unity", "AR/VR/MR", "Blender", "Hololens", "C#"]
    },
    {
        "id": 10,
        "path": "threedeepro",
        "image": "threedeepro",
        "title": "THREEDEEPRO",
        "duration": "a 3 weeks project", 
        "time": "April 2024",
        "Team": "Ivery Chen, Dave Song, Sohum Sanu, Viviana Wei",
        "Role": "UIUX Design",
        "Tools": "Figma, Loom",
        "eventName": "Threedeepro",
        "description": "A computer vision, on-paper drawing based 3D modelling tool",
        "categories": [ "Backend", "Prototyping", "Research", "Computer Vision", "Computer Graphics", "Python", "Javascript"]
    },
    {
        "id": 11,
        "path": "crystal",
        "image": "crystal2",
        "title": "CRYSTAL GEN",
        "duration": "a 3 weeks project", 
        "time": "April 2024",
        "Team": "Ivery Chen, Dave Song, Sohum Sanu, Viviana Wei",
        "Role": "UIUX Design",
        "Tools": "Figma, Loom",
        "eventName": "Procedurally generate crystals",
        "description": "A tool that generates crystals.",
        "categories": [ "Backend", "Computer Graphics", "C++", "QTCreator"]
    },
    {
        "id": 12,
        "path": "usd",
        "image": "usd",
        "title": "USD MATERIAL TOOL",
        "duration": "a 3 weeks project", 
        "time": "April 2024",
        "Team": "Ivery Chen, Dave Song, Sohum Sanu, Viviana Wei",
        "Role": "UIUX Design",
        "Tools": "Figma, Loom",
        "eventName": "Texture to Material.usd tool",
        "description": "A tool that takes in models and textures and auto-create usd material files.",
        "categories": [ "Backend", "Prototyping", "Computer Graphics", "USD", "Python"]
    },
    {
        "id": 13,
        "path": "reel",
        "image": "reel",
        "title": "TECH ART REEL",
        "duration": "a 3 weeks project", 
        "time": "April 2024",
        "Team": "Ivery Chen, Dave Song, Sohum Sanu, Viviana Wei",
        "Role": "UIUX Design",
        "Tools": "Figma, Loom",
        "eventName": "Tech Artist Reel",
        "description": "Tech Art Reel",
        "categories": ["Blender", "Maya","Houdini", "Substance Painter", "Nuke", "Unity", "Katana", "Premiere Pro", "After Effects"]
    },

];

export default jsonData;
