const images = {
    lookIvery: require('./assets/lookivery_render12_256.png'),
    lookiveryintro: require('./assets/lookiveryintro.png'),
    intro: require('./assets/intro.png'),
    partiful: require('./assets/partiful_mu.png'),
    partiful_problem: require('./assets/partiful_problem.png'),
    partiful_sketch1: require('./assets/partiful_sketch1.png'),
    partiful_sketch2: require('./assets/partiful_sketch2.png'),
    partiful_wireframe1: require('./assets/partiful_wireframe1.png'),
    partiful_wireframe2: require('./assets/partiful_wireframe2.png'),
    partiful_wireframe3: require('./assets/partiful_wireframe3.png'),
    partiful_wireframe4: require('./assets/partiful_wireframe4.png'),
    partiful_wireframe5: require('./assets/partiful_wireframe5.png'),
    partiful_styleguide: require('./assets/partiful_styleguide.png'),
    partiful_event1: require('./assets/partiful_styleguide.png'),
    partiful_event2: require('./assets/partiful_styleguide.png'),
    partiful_basic_hifi: require('./assets/partiful_basic_hifi.png'),
    partiful_basic_hifi2: require('./assets/partiful_basic_hifi2.png'),
    partiful_basic_hifi3: require('./assets/partiful_basic_hifi3.png'),
    partiful_map_design: require('./assets/partiful_map_design.png'),
    partiful_map_design_past: require('./assets/partiful_map_design_past.png'),
    partiful_notif: require('./assets/partiful_notif.png'),
    partiful_notif_past: require('./assets/partiful_notif_past.png'),
    partiful_notif_expanded_past: require('./assets/partiful_notif_expanded_past.png'),
    foam: require('./assets/foam_mu.png'),
    foam_compare: require('./assets/foam_compare.png'),
    foam_favourites: require('./assets/foam_favourites.png'),
    foam_landing_expanded: require('./assets/foam_landing_expanded.png'),
    foam_landing: require('./assets/foam_landing.png'),
    foam_figma_favourites: require('./assets/foam_figma_favourites.png'),
    foam_figma_landing: require('./assets/foam_figma_landing.png'),
    sf: require('./assets/sf_mu.png'),
    sf_problem:require('./assets/sf_problem.png'),
    sf_ipad_mu:require('./assets/sf_ipad_mu.png'),
    sf_ipad:require('./assets/sf_ipad.png'),
    sf_ipadhigh2:require('./assets/sf_ipadhigh2.png'),
    sf_ipadlow:require('./assets/sf_ipadlow.png'),
    sf_iphone_mu:require('./assets/sf_iphone_mu.png'),
    sf_iphone:require('./assets/sf_iphone.png'),
    sf_mac_mu:require('./assets/sf_mac_mu.png'),
    sf_mac:require('./assets/sf_mac.png'),
    sf_machigh2:require('./assets/sf_machigh2.png'),
    sf_maclow:require('./assets/sf_maclow.png'),
    sf_phonehigh2:require('./assets/sf_phonehigh2.png'),
    sf_phonelow:require('./assets/sf_phonelow.png'),
    sf_speedy1:require('./assets/sf_speedy1.png'),
    sf_speedy2:require('./assets/sf_speedy2.png'),
    sf_styleguide:require('./assets/sf_styleguide.png'),
    drivealive: require('./assets/drivealive-mu.png'),
    panda: require('./assets/panda.png'),
    skim: require('./assets/skim.png'),
    bayer: require('./assets/bayer.png'),
    magritte: require('./assets/magritte.png'),
    nasa_suits: require('./assets/nasa_suits.png'),
    threedeepro: require('./assets/threedeepro.png'),
    crystal2: require('./assets/crystal2.png'),
    usd: require('./assets/usd.png'),
    reel: require('./assets/reel.jpg'),

  };

  
  export default images;