const images = {
    lookIvery: require('./assets/lookivery_render12_256.png'),
    lookiveryintro: require('./assets/lookiveryintro.png'),
    intro: require('./assets/intro.png'),
    partiful: require('./assets/partiful_mu.png'),
    partiful_problem: require('./assets/partiful_problem.png'),
    partiful_sketch1: require('./assets/partiful_sketch1.png'),
    partiful_sketch2: require('./assets/partiful_sketch2.png'),
    partiful_wireframe1: require('./assets/partiful_wireframe1.png'),
    partiful_wireframe2: require('./assets/partiful_wireframe2.png'),
    partiful_wireframe3: require('./assets/partiful_wireframe3.png'),
    partiful_wireframe4: require('./assets/partiful_wireframe4.png'),
    partiful_wireframe5: require('./assets/partiful_wireframe5.png'),
    partiful_styleguide: require('./assets/partiful_styleguide.png'),
    partiful_event1: require('./assets/partiful_styleguide.png'),
    partiful_event2: require('./assets/partiful_styleguide.png'),
    partiful_basic_hifi: require('./assets/partiful_basic_hifi.png'),
    partiful_basic_hifi2: require('./assets/partiful_basic_hifi2.png'),
    partiful_basic_hifi3: require('./assets/partiful_basic_hifi3.png'),
    partiful_map_design: require('./assets/partiful_map_design.png'),
    partiful_map_design_past: require('./assets/partiful_map_design_past.png'),
    partiful_notif: require('./assets/partiful_notif.png'),
    partiful_notif_past: require('./assets/partiful_notif_past.png'),
    partiful_notif_expanded_past: require('./assets/partiful_notif_expanded_past.png'),
    foam: require('./assets/foam_mu.png'),
    sf: require('./assets/sf_mu.png'),
    drivealive: require('./assets/drivealive-mu.png'),
    panda: require('./assets/panda.png'),
    skim: require('./assets/skim.png'),
    bayer: require('./assets/bayer.png'),
    magritte: require('./assets/magritte.png'),
    nasa_suits: require('./assets/nasa_suits.png'),
    threedeepro: require('./assets/threedeepro.png'),
    crystal2: require('./assets/crystal2.png'),
    usd: require('./assets/usd.png'),
    reel: require('./assets/reel.jpg'),

  };

  
  export default images;